### ISSUE TITLE
update cyber_glove_calibrator to work on kinetic

### ISSUE THREAD

**Issue by azompas** [shadow-robot/sr-visualization#147]

**Comment by robotlinker** [comment]
Hi, I get problem when loading the calibrator plugin in rqt.

PluginManager._load_plugin() could not load plugin "sr_gui_cyberglove_calibrator/Cyberglove_Calibrator":
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 99, in load
    self._load()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 101, in load
    return class_ref(plugin_context)
  File "/home/conghui/sr_ws/src/sr-visualization/advanced/sr_gui_cyberglove_calibrator/src/sr_gui_cyberglove_calibrator/cyberglove_calibrator.py", line 316, in __init__
    self.calibrer = CybergloveCalibrer(description_function=None, nb_sensors=self.nb_sensors)
  File "/home/conghui/sr_ws/src/sr-visualization/advanced/sr_gui_cyberglove_calibrator/src/sr_gui_cyberglove_calibrator/cyberglove_calibrer.py", line 127, in __init__
    self.cyberglove = Cyberglove(nb_sensors=self.nb_sensors)
  File "/home/conghui/sr_ws/src/sr-visualization/advanced/sr_gui_cyberglove_calibrator/src/sr_gui_cyberglove_calibrator/cyberglove_library.py", line 109, in __init__
    self.createMap()
  File "/home/conghui/sr_ws/src/sr-visualization/advanced/sr_gui_cyberglove_calibrator/src/sr_gui_cyberglove_calibrator/cyberglove_library.py", line 145, in createMap
    for index in range(0, len(self.raw_messages[0].name)):
IndexError: list index out of range
